# Generated by Django 5.2.14 on 2026-05-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post_text', models.TextField(blank=True)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('times_seen', models.PositiveIntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['times_seen', 'imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jkh_relevance', models.CharField(choices=[('yes', 'Да, относится к ЖКХ'), ('no', 'Нет, не относится к ЖКХ'), ('unsure', 'Не уверен(а)')], max_length=20)),
                ('jkh_topic', models.CharField(choices=[('not_jkh', 'Не ЖКХ'), ('heating_hot_water', 'Отопление и горячая вода'), ('cold_water_sewerage', 'Холодная вода и канализация'), ('waste_cleaning', 'Мусор и уборка'), ('house_common_property', 'Подъезд, лифт, крыша, подвал'), ('yard_area', 'Двор и придомовая территория'), ('payments_tariffs', 'Тарифы, квитанции, счетчики'), ('management_company', 'Работа УК/ТСЖ'), ('public_authorities', 'Работа администрации/госорганов'), ('other_jkh', 'Другое ЖКХ')], max_length=40)),
                ('authority_aspect', models.CharField(choices=[('not_applicable', 'Не применимо'), ('no_action', 'Бездействие'), ('slow_response', 'Затягивание сроков'), ('poor_quality', 'Некачественная работа'), ('communication', 'Информирование и ответы гражданам'), ('tariff_policy', 'Тарифы и начисления'), ('supervision', 'Контроль и надзор'), ('positive_feedback', 'Положительная оценка работы'), ('other', 'Другое')], max_length=40)),
                ('sentiment', models.CharField(choices=[('negative', 'Негативная'), ('neutral', 'Нейтральная'), ('positive', 'Позитивная'), ('mixed', 'Смешанная/неоднозначная')], max_length=20)),
                ('appeal_type', models.CharField(choices=[('complaint', 'Жалоба'), ('question', 'Вопрос'), ('request', 'Просьба'), ('demand', 'Требование'), ('suggestion', 'Предложение'), ('gratitude', 'Благодарность'), ('opinion', 'Мнение'), ('info', 'Информирование'), ('other', 'Другое')], max_length=30)),
                ('responsible_party', models.CharField(choices=[('management_company', 'УК/ТСЖ'), ('resource_provider', 'Ресурсоснабжающая организация'), ('local_administration', 'Администрация'), ('housing_inspection', 'Госжилинспекция/надзор'), ('waste_operator', 'Регоператор по мусору'), ('residents', 'Жители/соседи'), ('specific_person', 'Конкретное лицо'), ('unknown', 'Неясно'), ('not_applicable', 'Не применимо')], max_length=40)),
                ('sarcasm', models.CharField(choices=[('no', 'Нет'), ('yes', 'Да'), ('unsure', 'Не уверен(а)')], max_length=20)),
                ('quality', models.CharField(choices=[('normal', 'Обычная запись'), ('difficult', 'Сложная/спорная'), ('spam', 'Мусор/спам'), ('duplicate', 'Дубликат'), ('no_context', 'Не хватает контекста')], default='normal', max_length=30)),
                ('student_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Ожидает проверки'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_annotations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.sourcerecord')),
            ],
            options={
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('award', 'Начисление'), ('penalty', 'Штраф')], max_length=20)),
                ('points', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='annotation.annotation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scores', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('admin', 'Администратор разметки')], default='student', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('public_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('record', 'student'), name='unique_annotation_per_student_record'),
        ),
    ]
