# Generated by Django 5.2.14 on 2026-05-19 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcerecord',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_source_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sourcerecord',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
