# Generated by Django 5.2.14 on 2026-05-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_source_record_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='is_deleted_post_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scoreevent',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='annotation.annotation'),
        ),
    ]
