# Generated by Django 5.2.14 on 2026-06-06 22:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_annotationcampaign_sourcerecord_sampling_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmsuArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('area_type', models.CharField(default='Муниципальное образование', max_length=80)),
                ('region', models.CharField(default='Нижегородская область', max_length=120)),
                ('head_name', models.CharField(blank=True, max_length=160)),
                ('leadership', models.JSONField(blank=True, default=list)),
                ('territory_area_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('population', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('geometry', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OmsuDashboardSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('omsu_score', models.IntegerField(default=0)),
                ('previous_omsu_score', models.IntegerField(default=0)),
                ('omsu_negative_probability', models.FloatField(default=0.0)),
                ('comments_total', models.PositiveIntegerField(default=0)),
                ('comments_last_day', models.PositiveIntegerField(default=0)),
                ('negative_total', models.PositiveIntegerField(default=0)),
                ('neutral_total', models.PositiveIntegerField(default=0)),
                ('positive_total', models.PositiveIntegerField(default=0)),
                ('top_topics', models.JSONField(blank=True, default=list)),
                ('charts', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='annotation.omsuarea')),
            ],
            options={
                'ordering': ['area__display_order', 'area__name'],
            },
        ),
        migrations.CreateModel(
            name='OmsuLatestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('omsu_score', models.IntegerField(default=0)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_comments', to='annotation.omsuarea')),
            ],
            options={
                'ordering': ['-published_at', '-received_at'],
            },
        ),
    ]
