# Generated by Django 5.2.14 on 2026-06-17 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_omsuarea_omsudashboardsnapshot_omsulatestcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('lookback_minutes', models.PositiveIntegerField(default=120)),
                ('max_sources', models.PositiveIntegerField(default=0)),
                ('max_posts_per_source', models.PositiveIntegerField(default=0)),
                ('max_comments_per_post', models.PositiveIntegerField(default=0)),
                ('sources_total', models.PositiveIntegerField(default=0)),
                ('sources_ok', models.PositiveIntegerField(default=0)),
                ('sources_failed', models.PositiveIntegerField(default=0)),
                ('posts_found', models.PositiveIntegerField(default=0)),
                ('comments_found', models.PositiveIntegerField(default=0)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('items_existing', models.PositiveIntegerField(default=0)),
                ('items_analyzed', models.PositiveIntegerField(default=0)),
                ('update_dashboard', models.BooleanField(default=False)),
                ('dry_run', models.BooleanField(default=False)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('vk_group', 'VK group')], default='vk_group', max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('screen_name', models.CharField(blank=True, db_index=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('parser_state', models.JSONField(blank=True, default=dict)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_sources', to='annotation.omsuarea')),
            ],
            options={
                'ordering': ['display_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment')], db_index=True, max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('post_external_id', models.CharField(blank=True, max_length=255)),
                ('post_url', models.URLField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('post_text', models.TextField(blank=True)),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at_raw', models.CharField(blank=True, max_length=255)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('cleaned_meta', models.JSONField(blank=True, default=dict)),
                ('taxonomy', models.JSONField(blank=True, default=dict)),
                ('taxonomy_confidence', models.JSONField(blank=True, default=dict)),
                ('omsu_score', models.IntegerField(default=0)),
                ('omsu_impact_class', models.CharField(blank=True, max_length=40)),
                ('omsu_negative_probability', models.FloatField(default=0.0)),
                ('omsu_decision', models.CharField(blank=True, max_length=40)),
                ('omsu_confidence_band', models.CharField(blank=True, max_length=40)),
                ('omsu_score_reason', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_items', to='annotation.omsuarea')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='annotation.monitoringrun')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='annotation.monitoringsource')),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at', 'id'],
                'indexes': [models.Index(fields=['source', 'item_type', 'external_id'], name='annotation__source__2114c7_idx'), models.Index(fields=['area', 'published_at'], name='annotation__area_id_d8f506_idx'), models.Index(fields=['omsu_decision', 'published_at'], name='annotation__omsu_de_f4af61_idx')],
            },
        ),
    ]
